from Types import TimeType, NumberBaristasType, ConsumerType, ConsumersServedType, CurrencyType
from typing import List

coffee_shop_state = {"name": "Coffee Shop State",
                     "notes": "There should be only one instance of this state in a simulation",
                     "variables": [{"type": NumberBaristasType,
                                    "name": "number_of_baristas",
                                    "description": "The current number of baristas on staff",
                                    "symbol": None,
                                    "domain": None},
                                   {"type": List[ConsumerType],
                                    "name": "queue",
                                    "description": "The queue of customers",
                                    "symbol": None,
                                    "domain": None},
                                   {"type": ConsumersServedType,
                                    "name": "customers_served",
                                    "description": "The number of customers served in an epoch",
                                    "symbol": None,
                                    "domain": None},
                                   {"type": CurrencyType,
                                    "name": "wages_accrued",
                                    "description": "The amount of wages that are accrued in an epoch",
                                    "symbol": None,
                                    "domain": None}]}
