"""{"name": "Coffee Shop State",
"notes": "There should be only one instance of this state in a simulation",
"variables": [{"type": number_baristas,
                "name": "number_of_baristas",
                "description": "The current number of baristas on staff",
                "symbol": ,
                "domain": },
               {"type": List[Consumer],
                "name": "queue",
                "description": "The queue of customers",
                "symbol": ,
                "domain": },
               {"type": consumers_served,
                "name": "customers_served",
                "description": "The number of customers served in an epoch",
                "symbol": ,
                "domain": },
               {"type": Currency,
                "name": "wages_accrued",
                "description": "The amount of wages that are accrued in an epoch",
                "symbol": ,
                "domain": }]}"""
